// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateProductReq struct {
	ProductName       string  `json:"product_name" validate:"required,min=4,max=128"`     // 产品名称
	ProductType       string  `json:"product_type" validate:"required,min=4,max=32"`      // 产品类型，如“股票型”“债券型”“混合型”“货币型”
	ProductSubType    string  `json:"product_sub_type" validate:"omitempty,min=4,max=32"` // 产品子类型，可选
	RiskLevel         string  `json:"risk_level" validate:"required,min=1,max=10"`        // 风险等级，如“R1”“R2”...
	ProductStatus     string  `json:"product_status" validate:"required,min=2,max=20"`    // 产品状态，如“正常”“发行中”
	Manager           string  `json:"manager" validate:"required,min=4,max=64"`           // 基金管理人
	Custodian         string  `json:"custodian" validate:"required,min=4,max=64"`         // 基金托管人
	PurchaseFeeRate   float64 `json:"purchase_fee_rate" validate:"required"`              // 前端申购费率
	RedemptionFeeRule string  `json:"redemption_fee_rule" validate:"required"`            // 赎回费率规则，JSON格式
	Description       string  `json:"description" validate:"omitempty"`                   // 产品说明书，可为空
}

type DeleteProductReq struct {
	ProductId string `path:"product_id"`
}

type GetProductDetailReq struct {
	ProductId string `path:"product_id"`
}

type ProductInfo struct {
	ProductId         string  `json:"product_id"`                 // 产品唯一标识
	ProductName       string  `json:"product_name"`               // 产品名称
	ProductType       string  `json:"product_type"`               // 产品类型
	ProductSubType    string  `json:"product_sub_type,optional"`  // 产品子类型
	RiskLevel         string  `json:"risk_level"`                 // 风险等级
	ProductStatus     string  `json:"product_status"`             // 产品状态
	Manager           string  `json:"manager"`                    // 基金管理人
	Custodian         string  `json:"custodian"`                  // 基金托管人
	PurchaseFeeRate   float32 `json:"purchase_fee_rate,optional"` // 申购费率
	RedemptionFeeRule string  `json:"redemption_fee_rule"`        // 赎回费率规则（JSON）
	Description       string  `json:"description"`                // 产品说明
	CreateTime        string  `json:"create_time"`                // 创建时间
	UpdateTime        string  `json:"update_time"`                // 更新时间
	CreateBy          int64   `json:"create_by"`                  // 创建人
}

type ProductListReq struct {
	Page           int    `form:"page,optional,default=1"`
	PageSize       int    `form:"page_size,optional,default=10"`
	SearchKeyWords string `form:"search_key_words,optional"` // 产品名称搜索关键词，最大128字符
	ProductType    string `form:"product_type,optional"`     // 产品类型，如"股票型""债券型""混合型""货币型"，长度4-32字
	ProductSubType string `form:"product_sub_type,optional"` // 产品子类型，根据实际业务细分，长度4-32字符
	RiskLevel      string `form:"risk_level,optional"`       // 产品风险等级，如"R1""R2""R3""R4""R5"，长度1-10字符
	ProductStatus  string `form:"product_status,optional"`   // 产品状态，如"正常""发行中""暂停申购""赎回""清算中"，长度2-20字符
	Manager        string `form:"manager,optional"`          // 基金管理人，如"天弘基金""南方基金"，长度4-64字符
	Custodian      string `form:"custodian,optional"`        // 基金托管人，如"中信银行"，长度4-64字符
}

type ProductListResp struct {
	Code  int           `json:"code"`
	Msg   string        `json:"msg"`
	Total int64         `json:"total"`
	List  []ProductInfo `json:"list"`
}

type Response struct {
	Code uint32      `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type UpdateProductReq struct {
	ProductId         string  `json:"product_id"`
	ProductName       string  `json:"product_name,optional"`
	ProductType       string  `json:"product_type,optional"`
	ProductSubType    string  `json:"product_sub_type,optional"`
	RiskLevel         string  `json:"risk_level,optional"`
	ProductStatus     string  `json:"product_status,optional"`
	Manager           string  `json:"manager,optional"`
	Custodian         string  `json:"custodian,optional"`
	PurchaseFeeRate   float32 `json:"purchase_fee_rate,optional"`
	RedemptionFeeRule string  `json:"redemption_fee_rule,optional"`
	Description       string  `json:"description,optional"`
}
