// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"WMSS/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建新产品
				Method:  http.MethodPost,
				Path:    "/api/product/create",
				Handler: CreateProductHandler(serverCtx),
			},
			{
				// 删除产品（逻辑删除）
				Method:  http.MethodDelete,
				Path:    "/api/product/delete/:product_id",
				Handler: DeleteProductHandler(serverCtx),
			},
			{
				// 获取产品详情
				Method:  http.MethodGet,
				Path:    "/api/product/detail/:product_id",
				Handler: GetProductDetailHandler(serverCtx),
			},
			{
				// 分页查询产品列表
				Method:  http.MethodPost,
				Path:    "/api/product/list",
				Handler: GetProductListHandler(serverCtx),
			},
			{
				// 更新产品信息
				Method:  http.MethodPost,
				Path:    "/api/product/update",
				Handler: UpdateProductHandler(serverCtx),
			},
		},
	)
}
